### ISSUE TITLE
Padding Above What We Do Block is Inconsistent

### ISSUE THREAD

**Issue by h-w-koenig** [Dezudio/dezudio-website#21]
2440:

1. Make consistent padding-top above all "WHAT WE DO" / "OUR APPROACH set to padding-top: 7rem; (this was inconsistent in our mockups but we want it to be the same)
2. Make consistent padding-bottom for each section div to padding-bottom: 6rem;

**Comment by h-w-koenig** [comment]
1920: 

1. Make consistent padding-top above all "WHAT WE DO" / "OUR APPROACH set to padding-top: 7rem; (this was inconsistent in our mockups but we want it to be the same)
2. Make consistent padding-bottom for each section div to padding-bottom: 6rem;

**Comment by raelynno** [comment]
Duplicate of #32
