### ISSUE TITLE
Footer logo

### ISSUE THREAD

**Issue by mrdirby** [Dezudio/dezudio-website#57]
In the mobile footer, I know we talked about this and can’t remember where we landed. It would be great for the D of the Dezudio logo to left-align to the rest of the text in the footer. Let me know if we should get you a new logo file.

**Comment by mrdirby** [comment]
@h-w-koenig I need the reversed logo white text. You send the dark logo.

**Comment by h-w-koenig** [comment]
@mrdirby Fixed! In your folder.
