### ISSUE TITLE
Home Understanding Title break after comma

### ISSUE THREAD

**Issue by mrdirby** [Dezudio/dezudio-website#58]
Is there a way to make “Understanding people, helping people understand” break at the comma instead of after “helping”?

@h-w-koenig There is a temporary fix for this that always forces a break after the comma. But at smaller breakpoints it forces a break when it isn't necessary. But this could be ok if you always want a break there. Review and let me know. 

There is another solution but it's more complicated because we need to add more modules to Tailwind CSS to allow this function. @merichar I could also just style this in the global css file. Anyway maybe there always should be a break after the comma.

**Comment by h-w-koenig** [comment]
@mrdirby I think it's working at every breakpoint except the smallest one, where it feels awkward to have it force break in the middle of the sentence. How hard is it to make an exception for the mobile size?

**Comment by mrdirby** [comment]
I just wrote the css for this in global.css. Just a few lines of code that cleans it up easily.
